### ISSUE TITLE
安装wsl2提示缺少ubuntu_wsl_splash.exe

### ISSUE THREAD

**Issue by liwenjie119** [ActiveIce/WSL2-Linux-Kernel#2]
运行.\ubuntu.exe --ui=tui安装wsl时，提示：
Splash executable [E:\ubuntu2\ubuntu_wsl_splash.exe] not found.
仅查到https://github.com/ubuntu/ubuntu-wsl-splash 这个项目，但是没有releases，也没太搞懂怎么编译得到ubuntu_wsl_splash.exe

**Comment by ActiveIce** [comment]
ubuntu_wsl_splash.exe not found is OK since we only use tui

**Comment by liwenjie119** [comment]
另一个问题，最新的内核安装时发现如此提示：
`E:\ubuntu>.\ubuntu.exe --ui=tui
Splash executable [E:\ubuntu\ubuntu_wsl_splash.exe] not found.
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 ???????????????????

Press any key to continue...`
并且换用新内核后之前安装的ubuntu提示：
`没有收到虚拟机或容器的回应，操作超时。
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT`
退回9月份左右内核是没问题的，中间由于有一段时间没更新或备份内核，不清楚是从哪一版出了问题，不知道大佬有没有遇到这个问题。

**Comment by liwenjie119** [comment]
> ubuntu_wsl_splash.exe not found is OK since we only use tui
我以为是缺少ubuntu_wsl_splash.exe导致无法正常启动，因为我遇到另一个问题，最新的内核安装时发现如此提示：


`E:\ubuntu>.\ubuntu.exe --ui=tui
Splash executable [E:\ubuntu\ubuntu_wsl_splash.exe] not found.
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370109
Error: 0x80370109 ???????????????????
Press any key to continue...`

并且换用新内核后之前安装的ubuntu提示：


`没有收到虚拟机或容器的回应，操作超时。
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT`

退回9月份左右内核是没问题的，中间由于有一段时间没更新或备份内核，不清楚是从哪一版出了问题，不知道大佬有没有遇到这个问题。


更正：Linux muxinghe 6.1.0-rc8-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Sat Dec 10 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux这个日期的内核是没有问题的

**Comment by ActiveIce** [comment]
Kernel IBT is enabled by default after linux v6.2-rc1. Try the latest build.
