### ISSUE TITLE
 Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/E_UNEXPECTED

### ISSUE THREAD

**Issue by liwenjie119** [ActiveIce/WSL2-Linux-Kernel#3]
感谢大佬的内核编译，一直很好用。不过最近遇到了这个报错：
灾难性故障
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/E_UNEXPECTED
如果.wslconfig文件注释掉自定义内核，使用官方内核，能正常使用wsl2

**Comment by ActiveIce** [comment]
Use latest build

**Comment by liwenjie119** [comment]
> Use latest build
最近有出现新的问题
没有收到虚拟机或容器的回应，操作超时。
Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT
